### ISSUE TITLE
Unable to list files on the FTP server ... Getting the following error

### ISSUE THREAD

**Issue by vedantbarve** [salim-lachdhaf/dartFTP#13]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 0: -1
E/flutter (30359): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (30359): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (30359): #2      TransferUtil.parsePortPASV
transfer_util.dart:26
E/flutter (30359): #3      TransferUtil.parsePort
transfer_util.dart:5
E/flutter (30359): #4      FTPDirectory.listDirectoryContent

**Comment by salim-lachdhaf** [comment]
Please check v3.0.0
